### PR TITLE
Fix highlighting of char lists with escaped quotes

### PR DESCRIPTION
**Pull request by flupke**

### CODE REVIEW

**Comment by LnL7** [comment]
This seems to break [one of the tests](https://github.com/elixir-lang/vim-elixir/blob/master/spec/syntax/list_spec.rb#L4).
Could you write a test or give an example of the issue.

**Comment by flupke** [comment]
Yup, I just found out about #100, another pull request was already rejected for this issue. Investigating why the tests are broken now...

**Comment by LnL7** [comment]
I have a feeling the list test only passed by accident, we probably need some more tests for strings.

**Comment by flupke** [comment]
Yes it looks like a typo in the test:
```
'"\'
var = 1
```
The string is not closed. I'm not sure what the test was trying to demonstrate though: `List syntax should properly handle "\\\\" inside [???]`

**Comment by flupke** [comment]
Oh, I see, the backspace is not properly escaped in the test.

**Comment by LnL7** [comment]
I think the test is to check if in `'\\'` the backslash is escaped instead of the quote

**Comment by flupke** [comment]
Yes, so I think my fix is correct.

**Comment by LnL7** [comment]
Indeed, you have to escape for ruby aswell.

**Pull request merged**
