### PR TITLE
fixed typo in 'indentkeys'

### PR DESCRIPTION
**Pull request by nhooyr**

### CODE REVIEW

**Comment by jbodah** [comment]
@nhooyr did this break under a specific case? Based on the help docs for `indetkeys-format` I believe this was intended

**Comment by nhooyr** [comment]
Hmm, you are correct. Indentation was not functioning correctly for me on hitting `<CR>` until I made this change. I'll look into it further and let you know what I find.

**Comment by jbodah** [comment]
A few things to check:

Are you on HEAD? Does it still happen with other plugins disabled?

If so, an example would be helpful. I'm currently doing a large pass at the indent code

**Comment by nhooyr** [comment]
I can't seem to reproduce. Must have been user error, sorry for the noise

**Comment by jbodah** [comment]
No worries 👍

**Pull request closed without merging**
