### PR TITLE
Skip vim folds when indenting

### PR DESCRIPTION
**Pull request by gasparch**
using vim in foldmethod=marker mode causes problems with code

```
def foo() do # {{{
  bar()
end # }}}
```

pressing `O` on line `bar()` creates wrong indent because of {{{ mistakenly taken to be part of tuple.

```
def foo() do # {{{
  bar()
end # }}}
```

specifically mark them as `elixirFold` syntax group and skip them when detecting indent level.

### CODE REVIEW

**Comment by kassio** [comment]
I'm not sure we should add this code. This is too specific to vim, and to be honest I don't suggest anyone to use vim fold marks in any language but `vim-script`.
Just to understand better, do you really commit code with these markers?

**Comment by gasparch** [comment]
I personally do :) may be it is not a best practice, yep.

Why I'm happy with them - it allows to fold all clauses of functions together, and not one by one. So, more logical folds, not some vim plugin decided to do folding.

**Comment by gasparch** [comment]
May be I can contribute with something like http://twinside.github.io/vim-haskellFold/

**Comment by kassio** [comment]
@gasparch interesting. Yeah, IMHO i think this is a little out of the scope of this plugin. But the community can appreciate a new plugin for this. 😄

**Pull request closed without merging**
