### PR TITLE
Indent performance

### LINKED ISSUE #334: Indent speed
Revisiting indent speed. Here's a recent profile log. One idea is to only check the skip expression if a match is found instead of every character (which is what I assume vim does)

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
  166   4.243429   0.035575  elixir#indent()
10507   3.534472             elixir#indent#is_string_or_comment()
 9972   3.517646   0.126857  elixir#indent#searchpair_back_skip()
  361   2.985598   0.364454  elixir#indent#searchpair_back()
   78   1.739187   0.003423  elixir#indent#handle_inside_data_structure()
   74   1.637481   0.001203  elixir#indent#handle_inside_parens()
   78   0.982898   0.086396  elixir#indent#searchpairpos_back()
   86   0.287238   0.001966  elixir#indent#handle_inside_keyword_block()
   81   0.264782   0.001816  elixir#indent#handle_inside_fn()
   73   0.143961   0.026293  elixir#indent#handle_inside_generic_block()
  165   0.062706   0.002761  elixir#indent#handle_starts_with_end()
    8   0.038509   0.000694  airline#check_mode()
    2   0.037343   0.004260  airline#highlighter#highlight()
 1895   0.027750             elixir#indent#debug()
  154   0.025063   0.007180  airline#highlighter#exec()
  285   0.021528   0.006755  elixir#indent#ends_with()
  125   0.020884   0.002262  elixir#indent#handle_following_trailing_do()
  589   0.020391   0.008199  elixir#indent#starts_with()
  258   0.018968   0.005507  airline#highlighter#get_highlight()
   50   0.016118   0.001567  <SNR>65_exec_separator()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
10507              3.534472  elixir#indent#is_string_or_comment()
  361   2.985598   0.364454  elixir#indent#searchpair_back()
 9972   3.517646   0.126857  elixir#indent#searchpair_back_skip()
   78   0.982898   0.086396  elixir#indent#searchpairpos_back()
  166   4.243429   0.035575  elixir#indent()
 1895              0.027750  elixir#indent#debug()
   73   0.143961   0.026293  elixir#indent#handle_inside_generic_block()
  516              0.012080  <SNR>65_get_syn()
  589   0.020391   0.008199  elixir#indent#starts_with()
  154   0.025063   0.007180  airline#highlighter#exec()
  285   0.021528   0.006755  elixir#indent#ends_with()
  258   0.018968   0.005507  airline#highlighter#get_highlight()
  728              0.004591  <SNR>65_Get()
    2   0.037343   0.004260  airline#highlighter#highlight()
   78   1.739187   0.003423  elixir#indent#handle_inside_data_structure()
  165   0.062706   0.002761  elixir#indent#handle_starts_with_end()
 1098              0.002735  elixir#indent#keyword()
  125   0.020884   0.002262  elixir#indent#handle_following_trailing_do()
   86   0.003381   0.002226  elixir#indent#handle_starts_with_binary_operator()
   86   0.287238   0.001966  elixir#indent#handle_inside_keyword_block()
```

### PR DESCRIPTION
**Pull request by jbodah**
Re-opened version of #341. This PR attempts to fix #334

TODO:

- [ ] profile a large file without a lot of doc blocks

### CODE REVIEW

**Comment by gasparch** [comment]
Tested on really big file (90k lines of unit tests :). 
Took 236.573156728 seconds to indent. Whereas large_file.ex you posted takes 12 sec on my machine.

Attaching the profiling results here: [profile.txt](https://github.com/elixir-lang/vim-elixir/files/1088648/profile.txt)

You can see that internal loop in `elixir#indent()` is called 42k times, thus such high total time. 

In general indenting feels much faster. In the end of the file it causes 0.3-0.5 sec pause on each insert, which is somehow tolerable. I think caching can decrease this as well.

**Comment by jbodah** [comment]
Thanks for the profile stack. From that trace it looks like `elixir#indent` is called 2799 times which sounds normal (once per line). I'm surprised that we don't see more time split up into the other functions there. I'll try and find a similar file to compare with

**Comment by jbodah** [comment]
@gasparch how does `bin/profile` perform for you if you remove the `with_block` handler?

**Comment by jbodah** [comment]
Closing, this changeset is way too drastic. We can get better performance by canceling searchpair early. This isn't perfect, but with a sufficient stopline range (say only look back 20 lines or something) then it handles most cases well. There might be other ways we can compute that range too

**Pull request closed without merging**
