### PR TITLE
Improve ftplugin

### PR DESCRIPTION
**Pull request by thinca**
I participated in [Elixir Conf Japan 2017](http://www.elixirconf.jp/), and I thought I'd like to contribute to Elixir.
I don't know much about Elixir.  But I'm a Vim user.  Therefore I fixed and improved ftplugin.

Sorry this PR includes some improvements and fixes.  If you want to merge only some commits, please tell me commits you'd like to drop.  Or cherry-pick commits freely :)

### CODE REVIEW

**Comment by jbodah** [comment]
Hey @thinca, thanks for this! Would you be able to explain a little bit of what is going on here (e.g. what was happening before, what this improvement changes and why it is better)?

**Comment by thinca** [comment]
> Set b:undo_ftplugin

`b:undo_ftplugin` should be set.  (`:help b:undo_ftplugin`)

> Fix b:undo_ftplugin in eelixir

String concatenation operator is missed.  Next line is ignored as a comment.

> Move GetElixirFilename function to autoload

Improve performance (a little).

> Better way to enable filetype plugins in spec

Use Vim's standard way. (`:help :filetype-overview`)

> Set some options at ftplugin instead of ftdetect

You should not put `autocmd FileType` in ftdetect.  This is ftplugin's work.

> Use relative path for 'path' option 

`'path'` option can specify relative path.  (`:help 'path'`)
This way can follow user's `:cd`.

> Smart way to get lines

Refactoring.

-----
Hmm, Travis build failed, however my Travis succeeded.
https://travis-ci.org/thinca/vim-elixir/builds/219948337

**Comment by jbodah** [comment]
> Hmm, Travis build failed, however my Travis succeeded.
https://travis-ci.org/thinca/vim-elixir/builds/219948337

This is a known issue with this repo. I'll pull these changes down and just do a quick sanity check over the next day or two and get it in. Thanks again!

**Comment by jbodah** [comment]
Really sorry this took so long to get to - plan to test this locally today and merge if everything is :100:

**Comment by jbodah** [comment]
Merging, thanks!

**Pull request merged**
