### PR TITLE
Nvim rplugin

### PR DESCRIPTION
**Pull request by awetzel**
Not sure if a pull request is a good way to propose you this. The thing is I developed a NVim Host plugin for Elixir https://github.com/awetzel/neovim-elixir and with it included the simple plugin `/rplugin/elixir/elixir_plugin.ex` allows you to have : 

- omnicompletion with module and function documentation
- your application running inside your Vim
- live elixir interpreter, keeping bindings across executions, which allows dynamic loading of your code into your running app without even saving the file thanks to the previous feature

Since adding the host plugin without using NVIM but only Vim causes no problem, maybe it is a good idea to have these features included in the "vim" plugin ?

this plugin does not at any "IDE" style configuration, but only 4 commands and 1 function : 
- command `:ElixirExec` taking selected range or the whole file to interpret it, keeping bindings in the plugin state for later evaluation. Support bang to reset bindings.
- command `:MixLoad` to find the nearest mix project of the current file and then load its beam and project. Without calling it, it loads the nearest mix project of `cwd`
- command `:MixStart` starts the application of current loaded mix project, optional argument to target a specific application to start
- command `:MixStop` stops the application of current loaded mix project optional argument to target a specific application to stop
- function : `ElixirComplete` to complete modules or functions with IEX helpers, with documentation on the preview window

Have a good day

### CODE REVIEW

**Comment by johnhamelink** [comment]
Hi there,

I tried using your fork, but I'm experiencing some issues with it:

When running `:UpdateRemotePlugins`, nvim hangs. Looking at `~/.nvimlog` reveals these messages:

```
2015/12/08 09:46:29 [info @ main:523] 85541 - Starting Neovim main loop.
2015/12/08 09:46:42 [error @ call_set_error:743] 85541 - msgpack-rpc: Channel was closed by the client
2015/12/08 10:01:29 [info @ main:523] 86033 - Starting Neovim main loop.
2015/12/08 10:01:33 [error @ forward_stderr:333] 86033 - Channel 2 stderr: Exception ignored in: 
2015/12/08 10:01:33 [error @ call_set_error:743] 86033 - msgpack-rpc: Channel was closed by the client
2015/12/08 10:01:33 [error @ call_set_error:743] 86033 - msgpack-rpc: Channel was closed by the client
2015/12/08 10:01:35 [info @ main:523] 86099 - Starting Neovim main loop.
2015/12/08 10:01:45 [error @ call_set_error:743] 86099 - msgpack-rpc: Channel was closed by the client
2015/12/08 10:01:45 [error @ call_set_error:743] 86099 - msgpack-rpc: Channel was closed by the client
2015/12/08 10:01:46 [info @ main:523] 86273 - Starting Neovim main loop.
2015/12/08 10:01:49 [error @ call_set_error:743] 86273 - msgpack-rpc: Channel was closed by the client
2015/12/08 10:02:08 [error @ call_set_error:743] 86273 - msgpack-rpc: Channel was closed by the client
2015/12/08 10:02:08 [error @ forward_stderr:333] 86273 - Channel 2 stderr: Exception ignored in: 
2015/12/08 10:02:08 [error @ call_set_error:743] 86273 - msgpack-rpc: Channel was closed by the client
2015/12/08 10:02:09 [info @ main:523] 86461 - Starting Neovim main loop.
2015/12/08 10:03:46 [error @ call_set_error:743] 86461 - msgpack-rpc: Channel was closed by the client
2015/12/08 10:03:46 [error @ call_set_error:743] 86461 - msgpack-rpc: Channel was closed by the client
2015/12/08 10:03:48 [info @ main:523] 86695 - Starting Neovim main loop.
2015/12/08 10:03:50 [error @ forward_stderr:333] 86695 - Channel 3 stderr: Exception ignored in: 
2015/12/08 10:03:50 [error @ call_set_error:743] 86695 - msgpack-rpc: Channel was closed by the client
2015/12/08 10:03:51 [error @ call_set_error:743] 86695 - msgpack-rpc: Channel was closed by the client
2015/12/08 10:03:51 [error @ forward_stderr:333] 86695 - Channel 2 stderr: Exception ignored in: 
2015/12/08 10:03:51 [error @ call_set_error:743] 86695 - msgpack-rpc: Channel was closed by the client
2015/12/08 10:04:03 [info @ main:523] 86783 - Starting Neovim main loop.
2015/12/08 10:04:07 [error @ forward_stderr:333] 86783 - Channel 3 stderr: /Users/kbrw/neovim-elixir/lib/api.ex:23: warning: redefining module NVim

2015/12/08 10:04:07 [error @ forward_stderr:333] 86783 - Channel 3 stderr: /Users/kbrw/neovim-elixir/lib/api.ex:43: warning: redefining module NVim.Buffer

2015/12/08 10:04:07 [error @ forward_stderr:333] 86783 - Channel 3 stderr: /Users/kbrw/neovim-elixir/lib/api.ex:43: warning: redefining module NVim.Tabpage

2015/12/08 10:04:07 [error @ forward_stderr:333] 86783 - Channel 3 stderr: /Users/kbrw/neovim-elixir/lib/api.ex:43: warning: redefining module NVim.Window

2015/12/08 10:04:07 [error @ forward_stderr:333] 86783 - Channel 3 stderr: /Users/kbrw/neovim-elixir/lib/api.ex:47: warning: redefining module NVim.Ext

2015/12/08 10:04:15 [info @ main:523] 87189 - Starting Neovim main loop.
```

The `/Users/kbrw` directory doesn't exist - something seems to be getting hard coded into the plugin.

**Comment by awetzel** [comment]
Hi actually there is a bug in the last neovim version : https://github.com/awetzel/neovim-elixir/issues/1
The bug is now fixed but I did not upgrade this branch.
I will do the update ASAP

**Comment by johnhamelink** [comment]
Thank you @awetzel, Looking forward to it!

**Comment by awetzel** [comment]
Hop I updated and rebased the branch

**Comment by johnhamelink** [comment]
@awetzel I can run `:UpdateRemotePlugins` now. Thanks :)

I am able to run `ctrl+x ctrl+o` on Objects like `List` and `Enum`, but I've found that modules I've defined cause vim to hang?

Screenshot example:

screen shot 2015-12-08 at 14 41 01

If I type `.` after writing a module, it also hangs but shows an empty string instead of `GoogleContactsToGrandstream.`:

screen shot 2015-12-08 at 14 40 50

**Comment by awetzel** [comment]
Ok I cannot reproduce your bug, the excepted behavior is 

capture d ecran 2015-12-08 a 15 52 33

I am working on stuffs to make debugging easier. 

I use nvim with the Elixir rplugin every day since last year and never encounter  your issue so : 
- it could be a version mismatch problem
- or a bug in the rplugin autocomplete function, it is actually a small function so it should not be so difficult to debug.

**Comment by johnhamelink** [comment]
Thanks @awetzel I will have a go at fixing it tomorrow if I have a chance & report back!

JH

**Comment by awetzel** [comment]
Actually since users seem to struggle to install it, I have created a simple repo in addition to vim-elixir, with an install script to recompile the plugin at every install. that way it is not needed to support old vim versions. https://github.com/awetzel/elixir.nvim

**Comment by kassio** [comment]
Since you created a new nvim plugin I think we can close this now, right?

And thank you for the awesome new plugin, I guess it's better be splitted as you created.

**Comment by awetzel** [comment]
Yes I think it is also better splitted, I 've just close the PR

**Pull request closed without merging**
