### PR TITLE
syntax: highlight "into:" as inline block

### LINKED ISSUE #312: syntax: func references screw up trailing keyword highlight
`into` highlight is incorrect

```ex
  defp atomize_keys(map), do: for kvp <- map, do: &atomize_key/1, into: %{}
```

### PR DESCRIPTION
**Pull request by mhinz**
Fixes #312

### CODE REVIEW

**Comment by jbodah** [comment]
LGTM - `elixirBlockInline` seems like the wrong approach to me in the long-term however. Macros can accept any keyword arguments, so there is an unbounded set of things we'd have to account for. I think the right long-term approach would be to lump these into `elixirAtom`s

**Comment by mhinz** [comment]
Let's fix it right away then!

The latest commit simply removes the whole `elixirBlockInline` syntax group which makes the code to fall back to `elixirAtom` instead.

**Comment by jbodah** [comment]
One last thing - would you mind adding a test case for the syntax of `into:` in case of regressions when refactoring? Otherwise this looks 💯

**Comment by mhinz** [comment]
Like this?

BTW, another thing that comes to mind.. in the case of `foo: bar`, the `:` also belongs to `elixirAtom`. Is that what we want?

**Comment by jbodah** [comment]
> BTW, another thing that comes to mind.. in the case of foo: bar, the : also belongs to elixirAtom. Is that what we want?

I'm not sure tbh. I think yes but I don't feel strongly right now and would be happy with going finer grain if we had people interested in that, but it hasn't come up yet through any requests AFAIK

**Comment by mhinz** [comment]
Does that mean _yes_ or _no_ for the colon question? :)

**Comment by jbodah** [comment]
For what it's worth, redcarpet seems to do this too ^

**Comment by mhinz** [comment]
Yeah, I like this change.

It makes sense to highlight `do:`, used in an actual atom context, differently from the `do` macro that is used for structural purposes.

**Pull request merged**
